### ISSUE TITLE
`yarn build` fails

### ISSUE THREAD

**Issue by joe733** [balucio/dnsmasq-webgui#31]
```console
$ yarn build
  yarn run v1.22.19
  $ react-scripts build
  Creating an optimized production build...
  Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:69:19)
      at Object.createHash (node:crypto:138:10)
      at module.exports ($HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/util/createHash.js:135:53)
      at NormalModule._initBuildHash ($HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/NormalModule.js:417:16)
      at handleParseError ($HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/NormalModule.js:471:10)
      at $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/NormalModule.js:503:5
      at $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/NormalModule.js:358:12
      at $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
      at iterateNormalLoaders ($HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
      at iterateNormalLoaders ($HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
  $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/react-scripts/scripts/build.js:19
    throw err;
    ^

  Error: error:0308010C:digital envelope routines::unsupported
      at new Hash (node:internal/crypto/hash:69:19)
      at Object.createHash (node:crypto:138:10)
      at module.exports ($HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/util/createHash.js:135:53)
      at NormalModule._initBuildHash ($HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/NormalModule.js:417:16)
      at $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/NormalModule.js:452:10
      at $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/webpack/lib/NormalModule.js:323:13
      at $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/loader-runner/lib/LoaderRunner.js:367:11
      at $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/loader-runner/lib/LoaderRunner.js:233:18
      at context.callback ($HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
      at $HOME/projects/balucio/dnsmasq-webgui/dns-webgui/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:55:103 {
    opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
    library: 'digital envelope routines',
    reason: 'unsupported',
    code: 'ERR_OSSL_EVP_UNSUPPORTED'
  }

  Node.js v20.0.0
  error Command failed with exit code 1.
  info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by balucio** [comment]
Hi, sorry I'm able to compile it using `yarn` version `1.22.10`.
Try to add
`export NODE_OPTIONS=--openssl-legacy-provider`
before compilation.

**Comment by joe733** [comment]
That worked.

Maybe you want to add these two lines to `README.md`.

```console
$ export NODE_OPTIONS=--openssl-legacy-provider
$ npx update-browserslist-db@latest
```

**Comment by balucio** [comment]
Ok :-) Tanks...
